import { PATH, PATH_COMPANY_EMPLOYEE, PATH_COMPANY_MANAGER } from '../../../constants/Paths/Path';

export const disable3DPath = [
  PATH.BOOTH_PAGE,
  PATH.PUBLICIZED_BOOTH_PAGE,
  PATH.BOOTH_PAGE,
  PATH_COMPANY_EMPLOYEE.JOB_FAIR_BOOTH_REVIEW,
  PATH_COMPANY_EMPLOYEE.DECORATE_BOOTH_PAGE,
  PATH_COMPANY_EMPLOYEE.ASSIGN_BOOTH_MAP_PAGE,
  PATH_COMPANY_MANAGER.ORGANIZE_JOB_FAIR_PAGE,
  PATH_COMPANY_MANAGER.REVIEW_MAP,
  PATH_COMPANY_MANAGER.TEMPLATE_DETAIL
];
