export const CompanyRegistrationStatus = {
  DRAFT: 'DRAFT',
  DELETED: 'DELETED',
  PENDING: 'PENDING',
  CANCEL: 'CANCEL',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  REQUEST_CHANGE: 'REQUEST_CHANGE'
}
