export const COMPANY_JOB_FAIR_STATUS = {
    'UNAVAILABLE': 'UNAVAILABLE',
    'REGISTRABLE': 'REGISTRABLE',
    "SUBMITTED": "SUBMITTED",
    "APPROVE": "APPROVE",
    "REJECT": "REJECT",
    "CHOOSE_BOOTH": "CHOOSE_BOOTH",
    "DECORATE_BOOTH": "DECORATE_BOOTH",
    "HAPPENING": "HAPPENING",
    "CLOSED": "CLOSED",
    "ATTENDED": "ATTENDED"
}