export const INTERVIEW_SCHEDULE_STATUS = {
  NOT_YET: 'NOT_YET',
  INTERVIEWING: 'INTERVIEWING',
  DONE: 'DONE',
  REQUEST_CHANGE: 'REQUEST_CHANGE'
};

export const SHIFT_HOUR = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19];
