export const NotificationType = {
  NOTI: 'NOTI',
  VISIT_JOB_FAIR: 'VISIT_JOB_FAIR',
  VISIT_JOB_FAIR_BOOTH: 'VISIT_JOB_FAIR_BOOTH',
  WAITING_ROOM: 'WAITING_ROOM',
  INTERVIEW_ROOM: 'INTERVIEW_ROOM',
  KICK_USER: 'KICK_USER',
  NEW_REFUND_REQUEST: 'NEW_REFUND_REQUEST',
  APPROVE_REFUND_REQUEST: 'APPROVE_REFUND_REQUEST',
  REJECT_REFUND_REQUEST: 'REJECT_REFUND_REQUEST'
};

export const NotificationAction = {
  ASSIGMENT: 'ASSIGNMENT',
  APPLICATION: 'APPLICATION',
  UN_ASSIGNMENT: 'UN_ASSIGNMENT'
};
