export const NotificationType = {
  NOTI: 'NOTI',
  VISIT_JOB_FAIR: 'VISIT_JOB_FAIR',
  VISIT_JOB_FAIR_BOOTH: 'VISIT_JOB_FAIR_BOOTH',
  WAITING_ROOM: 'WAITING_ROOM',
  INTERVIEW_ROOM: 'INTERVIEW_ROOM'
};
