export const NotificationType = {
  NOTI: 'NOTI',
  VISIT_JOB_FAIR: 'VISIT_JOB_FAIR',
  VISIT_JOB_FAIR_BOOTH: 'VISIT_JOB_FAIR_BOOTH',
  WAITING_ROOM: 'WAITING_ROOM',
  INTERVIEW_ROOM: 'INTERVIEW_ROOM',
  KICK_USER: 'KICK_USER'
};

export const NotificationAction = {
  ASSIGMENT: 'ASSIGNMENT',
  APPLICATION: 'APPLICATION',
  UN_ASSIGNMENT: 'UN_ASSIGNMENT',
  WARNING_TASK_MANAGER: 'WARNING_TASK_MANAGER',
  WARNING_TASK_SUPERVISOR_PROFILE: 'WARNING_TASK_SUPERVISOR_PROFILE',
  WARNING_TASK_SUPERVISOR_ASSIGN: 'WARNING_TASK_SUPERVISOR_ASSIGN',
  WARNING_TASK_DECORATOR: 'WARNING_TASK_DECORATOR'
};
