export const ENDPOINT_INTERVIEW_CONTROLLER = '/api/v1/interview';
export const ENDPOINT_INTERVIEW_SCHEDULE = `${ENDPOINT_INTERVIEW_CONTROLLER}/schedule`;
export const ENDPOINT_REQUEST_CHANGE_SCHEDULE = `${ENDPOINT_INTERVIEW_SCHEDULE}/change`;
