export const GET_ALL_SUBSCRIPTION_END_POINT = '/api/v1/subscriptions';
export const PURCHASE_SUBSCRIPTION_END_POINT = `${GET_ALL_SUBSCRIPTION_END_POINT}/pay`;
export const GET_ALL_COMPANY_SUBSCRIPTION = `${GET_ALL_SUBSCRIPTION_END_POINT}/company`;
export const GET_INVOICE = `${GET_ALL_SUBSCRIPTION_END_POINT}/invoice`;
