# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD
on:
  push:
    branches: [ main ]
    
jobs:
  build:
   name: Build
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: '14'
   - run: npm run build
     working-directory: ./jobfair-frontend
   - uses: actions/upload-artifact@v2
     with:
      name: frontend
      path: ./jobfair-frontend/build
    
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
    - uses: actions/download-artifact@v2
      with:
       name: frontend
       path: build
      env:
        AWS_S3_BUCKET: job-fair-online-frontend
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
