# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD
on:
  push:
    branches: [ CI-CD ]
    
jobs:
  build:
   name: Build
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
     with:
      path: CI-CD
   - uses: actions/setup-node@v2
     with:
      node-version: '14'
   - name: Build
     run: |
          cd jobfair-frontend
          touch .env.production
          echo ${{secrets.REACT_APP_API_URL}} >> .env.production
          echo ${{secrets.REACT_APP_AGORA_APP_ID}} >> .env.production
          npm install
          npm run build
   - uses: actions/upload-artifact@v2
     with:
      name: frontend
      path: ./jobfair-frontend/build
    
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-northeast-2
    - uses: actions/download-artifact@v2
      with:
       name: frontend
       path: build
    - run: aws s3 sync ./build s3://job-fair-online-frontend/

