# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD
on:
  push:
    branches: main
    
jobs:
  build:
   name: Build
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Setup nodejs
     run: | 
          sudo apt update
          curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
          sudo apt -y install nodejs
   - name: Build
     run: |
          cd jobfair-frontend/
          touch .env.production
          echo ${{secrets.REACT_APP_AGORA_APP_ID}} >> .env.production
          echo ${{secrets.REACT_APP_API_URL}} >> .env.production
          echo ${{secrets.ESLINT}} >> .env.production
          npm install --force
          npm run build
   - name: Deploy
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-northeast-2
   - name: Upload to S3
     run: aws s3 sync ./jobfair-frontend/build s3://job-fair-online-frontend/
   - name: Invalidate CloudFront
     run: aws cloudfront create-invalidation --distribution-id E26WIWU3XNUH4 --path "/*"

